language: php

php:
    - 7.0
    - 7.1
    - 7.2
    - hhvm

before_script:
    - composer self-update
    - composer install --dev --no-interaction

script:
    - vendor/bin/phpcs
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/php-coveralls -v
    - php vendor/bin/security-checker security:check
